### ISSUE TITLE
Crashes on app start

### ISSUE THREAD

**Issue by adarsh1001** [Akylas/com.akylas.documentscanner#37]
Unable to open the app (Build 16) after updating to Android 14. Not exactly sure if it's related to Android 14 directly or not though.

Log:

```
FATAL EXCEPTION: main
Process: com.akylas.documentscanner, PID: 4997
com.tns.NativeScriptException: Calling js method onBindViewHolder failed
TypeError: t.forEach is not a function
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(SourceFile:1)
	at com.tns.Runtime.callJSMethodImpl(Unknown Source:100)
	at com.tns.Runtime.callJSMethod(SourceFile:1)
	at com.tns.Runtime.callJSMethod(SourceFile:2)
	at com.tns.Runtime.callJSMethod(SourceFile:3)
	at com.tns.gen.com.nativescript.collectionview.AdapterInterface.onBindViewHolder(Unknown Source:17)
	at com.nativescript.collectionview.Adapter.onBindViewHolder(SourceFile:2)
	at com.nativescript.collectionview.Adapter.onBindViewHolder(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:155)
	at androidx.recyclerview.widget.RecyclerView$Recycler.i(SourceFile:72)
	at androidx.recyclerview.widget.RecyclerView$Recycler.j(SourceFile:62)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6)
	at androidx.recyclerview.widget.k0.b(SourceFile:54)
	at androidx.recyclerview.widget.GridLayoutManager.D(SourceFile:99)
	at androidx.recyclerview.widget.LinearLayoutManager.t(SourceFile:49)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:748)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(SourceFile:45)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:61)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:72)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
	at com.nativescript.collectionview.RecyclerView.onLayout(Unknown Source:0)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(SourceFile:377)
	at org.nativescript.widgets.GridLayout.onLayout(SourceFile:238)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(SourceFile:377)
	at org.nativescript.widgets.GridLayout.onLayout(SourceFile:238)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(SourceFile:377)
	at org.nativescript.widgets.ContentLayout.onLayout(Unknown Source:43)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4317)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3642)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2514)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9398)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1471)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1480)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1076)
	at android.view.Choreographer.doFrame(Choreographer.java:1004)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1447)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

**Comment by adarsh1001** [comment]
[crash-com-akylas-documentscanner-25_12-13-53-17_843.zip](https://github.com/Akylas/com.akylas.documentscanner/files/13765102/crash-com-akylas-documentscanner-25_12-13-53-17_843.zip)

**Comment by monnypython** [comment]
Same Problem here. Update the app on Android 13 and now it crashes on start.

**Comment by farfromrefug** [comment]
sorry to all of you. will fix as ddon as possibl

**Comment by farfromrefug** [comment]
@adarsh1001 @monnypython Sorry about that bug. Quite an ugly one. Should be fixed in new version

**Comment by adarsh1001** [comment]
Thanks @farfromrefug 🙏
